# ASP.NET Core

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

jobs:
- job: Test
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'

  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.203'

  - script: sudo apt-get update
    displayName: apt-get update

  - script: sudo apt-get install libcurl4-openssl-dev -y
    displayName: Install openssl

  - script: sudo apt-get install r-base -y
    displayName: Install r-base

  - script: sudo Rscript ./Linux/RPackagesInstall.R
    displayName: Install R Packages

# TEST
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'


  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '**/*[Tt]ests/*.csproj'
